# Generated by Django 5.1.6 on 2025-02-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRUD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('criada', models.DateTimeField(auto_now_add=True)),
                ('data_Entrega', models.DateTimeField()),
                ('finalizada', models.DateTimeField(null=True)),
            ],
        ),
    ]
