# Generated by Django 5.1.6 on 2025-02-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRUD", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crud",
            name="data_Entrega",
            field=models.DateTimeField(),
        ),
    ]
